#!/bin/zsh

# Some random seeds:
# 0x2ac4a88cb54956ad 0x337fee5ab97681b0 0xc7a93e3d4659a04f 0x63ba3f7a8a871e80 0x9346051b755d9994 0x4cb3a4475c6a21df 0xe5c4de8f09ec5eda 0x4e3554d545284126 0x6d93eddf288540a9 0x7f162b6419d84325 0x989ae787218f6f5e 0xa6c48681e292efa3 0xeac54f152aabff6d 0x7e3cb652120a0a55 0xc02f720892b0c4d4

for seed in "$@"
do
    # Avoid picking up any .dSym files by looing for trailing 'g' (clang)
    # or 'c' (gcc)
    for prog in tests/*[gc]
    do
	echo "$prog $seed > out/$prog:t.$seed.out"
    done
done | \
perl -e 'use strict; my @lines = (<>); while (@lines) { print splice @lines, rand(@lines), 1; }' | \
perl -lane 'BEGIN { print "# This Makefile was auto-generated by gen-tests.sh\n\nall: targets\n" } m{(tests/\S+)} or die "?"; print "$F[-1]: $1\n\t$_\n"; push @outs, $F[-1]; END { print "clean:\n\trm -f @outs\n"; print "targets: @outs\n"; }' > Makefile.test

mkdir -p out
