#!/bin/zsh

GPLUSPLUS="g++-8 -Wall -O3 -march=native -std=c++17 -g"
CLANGPLUSPLUS="clang++ -Wall -O3 -march=native -std=c++17 -g"
CLANGLIBPATH=`which clang++`
CLANGLIBPATH=$CLANGLIBPATH:h/../include/c++/v1
GPLUSPLUS_USELIBCPP="-nostdinc++ -I$CLANGLIBPATH -nodefaultlibs -lc++ -lc++abi -lm -lc -lgcc_s -lgcc"  # Linux
GPLUSPLUS_USELIBCPP="-nostdinc++ -I$CLANGLIBPATH -nodefaultlibs -lc++ -lc++abi -lm -lSystem -lgcc"  # OS X

{

while read -A line
do
foreach method (`perl -ne 'print if s/^#.*if.*USE_//' bounded32.cpp`)
echo $GPLUSPLUS bounded32.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] -o bounded32.$line[2].$method.gcc
echo $CLANGPLUSPLUS bounded32.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] -o bounded32.$line[2].$method.clang
end
foreach method (STD)
echo $GPLUSPLUS bounded32.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] $GPLUSPLUS_USELIBCPP -o bounded32.$line[2].$method-libc++.gcc
echo $CLANGPLUSPLUS -stdlib=libc++ bounded32.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] -o bounded32.$line[2].$method-libc++.clang
end
done < schemes-32.dat

while read -A line
do
foreach method (`perl -ne 'print if s/^#.*if.*USE_//' bounded64.cpp`)
echo $GPLUSPLUS bounded64.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] -o bounded64.$line[2].$method.gcc
echo $CLANGPLUSPLUS bounded64.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] -o bounded64.$line[2].$method.clang
end
foreach method (STD)
echo $GPLUSPLUS bounded64.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] $GPLUSPLUS_USELIBCPP -o bounded64.$line[2].$method-libc++.gcc
echo $CLANGPLUSPLUS -stdlib=libc++ bounded64.cpp -Ipcg-cpp-master/include -DUSE_$method -DRNG_INCLUDE=$line[1] -DRNG_TYPE=$line[2] $line[3,-1] -o bounded64.$line[2].$method-libc++.clang
end
done < schemes-64.dat

} | perl -lane 'BEGIN { print "# This Makefile was auto-generated by gen-makefile.sh\n\nall: targets\n" } s/(["<])(.*?)([>"])/\\$1$2\\$3/g; m/(\w+\.cpp)/ or die "?"; print "$F[-1]: $1\n\t$_\n"; push @execs, $F[-1]; END { print "clean:\n\trm -f @execs\n"; print "targets: @execs\n"; }' > Makefile
